### ISSUE TITLE
Playback isn't working, and no thumbnails

### ISSUE THREAD

**Issue by poperigby** [pobthebuilder/resolve-flatpak#5] opened 2023-03-28 17:06 UTC
I installed the studio version of Davinci Resolve, and I'm running into some issues. When I try to play any file in the editor, it just won't. The scrubber will be stuck at the first part of the clip. Clips also don't have any thumbnails. I'm getting this in the Davinci Resolve log:

```
0x7ff4a2bd9640 | UI.GLInterop         | ERROR | 2023-03-28 10:04:03,498 | MainPlayer: Failed to create handle, not initialized.
```

I figured I would report here, because it might be an issue with the packaging.

**Comment by pobthebuilder** [comment] 2023-04-17 22:49
tested with the latest version and can't replicate this with Studio on Silverblue. did you get this working?

**Comment by pobthebuilder** [comment] 2023-04-18 00:05
this doesn't replicate on my nvidia desktop. 

replicated it on my amd machine. looks like this might be tied to opencl/opengl support using mesa drivers in flatpak; similar to issues seen in darktable, here:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1181

looks like we'd need amdgpu-pro driver opengl/opencl support in flatpak, but that doesn't seem to exist? there is some work on rocm ongoing here:
https://github.com/orowith2os/rocm-flatpak

i'm not really familiar with the amdgpu stack. i'll have a play around and see what i can do but we might be SoL on AMD cards?

**Comment by pobthebuilder** [comment] 2023-04-18 00:06
https://github.com/RadeonOpenCompute/ROCm/issues/1397

**Comment by UnisTorvalds** [comment] 2023-04-18 00:25
SoL is correct for OpenCL on AMD, at least until this [Rusticl patch](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21305) merges into Mesa, hopefully for the 23.3 release window.

I've messed with this issue for a long time.  ROCm [is dodgy](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/59) around OpenCL image support.  Installing only select OpenCL components from AMDGPU-PRO and/or ROCm through a script like [this one](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21305) (in order to avoid the entire proprietary stack) will get Darktable, LuxMark, and other OpenCL applications working on AMD, but not DaVinci Resolve as it looks for certain extensions which are (afaik) only present in the AMDGPU-PRO full driver stack.  However, AMDGPU-PRO itself is not a fool-proof solution because not all releases (e.g. the latest) support all cards (e.g. Vega).

It's been a bit of a headache for my particular setup here.  But I have high hopes for the Rusticl merge into Mesa.  Initial testing looks very promising.  You may wish to sit tight until the merge request linked above.  Then, simply including the Mesa library in the flatpak should do the trick for universal AMD support.

**Comment by poperigby** [comment] 2023-04-18 17:55
Yes, forgot to mention that it's an AMD machine.

**Comment by pobthebuilder** [comment] 2023-05-13 17:06
Not yet tested, but I created a ROCm Flatpak that should work to give us OpenCL with Flatpak on AMD:
https://github.com/pobthebuilder/rocm-flatpak
For you you will have to build it yourself.

**Comment by pobthebuilder** [comment] 2023-05-22 03:21
closing this. the issue is that the default freedesktop sdk mesa clover opencl doesn't work well for amd and doesn't yet provide rusticl opencl.
however, i built a rocm flatpak and this works fine on 3 different amd devices (desktop / laptop) using the ROCm OpenCL flatpak package i provided here:
https://github.com/pobthebuilder/rocm-flatpak
you will have to build it yourself which requires a big machine.

**Closed by pobthebuilder** 2023-05-22 03:21 UTC
